# Generated by Django 4.1.7 on 2023-05-31 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('medicine_type', models.CharField(choices=[('liquid', 'LIQUID'), ('tablet', 'TABLET'), ('capsules', 'CAPSULES'), ('drops', 'DROPS'), ('injection', 'INJECTION')], default='tablet', max_length=20)),
                ('price', models.FloatField()),
                ('medicine_arrived', models.DateField(default=datetime.date.today)),
                ('medicine_company', models.CharField(max_length=50)),
            ],
        ),
    ]
