# Generated by Django 4.1.7 on 2023-06-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0003_medicine_medicine_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_expiry',
        ),
    ]
